### ISSUE TITLE
Release #1 - Roadmap

### ISSUE THREAD

**Issue by Jones-S** [wearelucid/vuecid-nuxt-craft#3]
List of things that have to be done for the first release:
- [ ] SEO stuff
    - [ ] Check if facebook and google see the right content
- [ ] Previews
    - [ ] New posts
    - [ ] Refactor for existing posts (https://github.com/markhuot/craftql/issues/31#issuecomment-523856248) (use Craft token instead of craftql `drafts`
- [ ] Navigation
- [ ] Global settings
- [ ] Add `$ yarn remove-examples` to clean up examplary setup
- [ ] Get DB sync to work (remote/local) (not directly part of this repo)

**Comment by Jones-S** [comment]
Navigation:
[GraphQl Example:](http://cms.lucid.test/admin/craftql/browse?query=%0A%0A%7B%0A%20%20entries(section%3A%20%5Bpages%5D)%20%7B%0A%20%20%20%20uri%0A%20%20%20%20url%0A%20%20%20%20id%0A%20%20%20%20slug%0A%20%20%20%20title%0A%20%20%20%20enabled%0A%20%20%20%20status%0A%20%20%20%20descendants%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20slug%0A%20%20%20%20%7D%0A%20%20%20%20hasDescendants%0A%20%20%20%20level%0A%20%20%20%20%0A%20%20%20%20children%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20uri%0A%20%20%20%20%20%20children%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20ancestors%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20uri%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A).

[Navigation Craft Setup.pdf](https://github.com/wearelucid/vuecid-nuxt-craft/files/3554705/Navigation.Craft.Setup.pdf)

**Comment by Jones-S** [comment]
Remove graphql queries which break things after installation

**Comment by Jones-S** [comment]
Define what we want per default!
- [ ] susy

- Add susy grid toggler in base component

**Comment by Jones-S** [comment]
- styling: `global.scss` für template styling. you can delete them?
- To Dos: I'm Readme checkboxes.
- `gulp: setup` modernizr.
- scss `/*` comments remove on production
- globals.json > like navigations.json
- missing `home` slug -> 404 message in basePage extended info.

**Comment by FabianEllenberger** [comment]
- [ ] Navi Desktop (burger only on mobile)
- [ ] Apollo folder README.md with short description
- [ ] Breakpoints in variables.scss add comment how to add a new one
- [ ] generic.fonts.scss add comment in file
- [ ] bLazyMedia component (or just BMedia which is lazy by default)
- [ ] i18n SEO testing
