### ISSUE TITLE
Craft Previews

### ISSUE THREAD

**Issue by Jones-S** [wearelucid/vuecid-nuxt-craft#4]
- [x] Previews
    - [x] Refactor for existing posts (https://github.com/markhuot/craftql/issues/31#issuecomment-523856248) (use Craft token instead of craftql `drafts`
    - [ ] New posts preview: https://github.com/markhuot/craftql/issues/31#issuecomment-525704090 
    - [ ] Fix unavailable __typename in axios call for neo plugin: https://github.com/spicywebau/craft-neo/issues/173#issuecomment-530844912 (Maybe with neo and core craft graphql, but we need to wait for seomatic to support graphql too: https://github.com/nystudio107/craft-seomatic/issues/466

Note on `__typename`:
We could get a nasty fix by just asking not for the `typename` but rather for some special props that occur in this page Builder component:
For example:
```
<Highlights
        v-if="component.__typename === 'PageBuilderHighlights' || component.highlights"
        :component="component"
      />
```
Just checking component.highlights (which hopefully only occur in the `PageBuilderHighlights`...

Note on new entries:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/7059580/66138647-43e4cc80-e5ff-11e9-8f48-258ac237c4cb.png">
They have no slug, and therefore we currently can't query anything...

**Comment by Jones-S** [comment]
Everything has changed with core graphql...
